### ISSUE TITLE
Calls to /execute create a SEVERE log entry

### ISSUE THREAD

**Issue by nitincoded** [nitincoded/FlexiRepo#1]
Calling /execute causes a SEVERE log entry - the JDBC driver complains that there is no resultset by tossing an exception

This behavior is expected from /query if the SQL statement doesn't return a resultset (Eg. for a DML or DDL statement), but not from /execute

**Comment by redknitin** [comment]
Fix has been committed to the repo:
https://github.com/nitincoded/FlexiRepo/commit/a62c34c833350f3ecdbf0ef9a1c66b87d5413d45
